name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_flip_counter: ^0.2.1
  cupertino_icons: ^1.0.4
  fl_chart: ^0.40.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^9.2.0
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  material_palette:
    path: ../../material_palette/
  nil: ^1.1.1

dev_dependencies:
  build_runner: ^2.1.5
  build_web_compilers: ^3.2.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
